### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by Zamyatin** [hirohisa/atom-project-runner#6]
[Enter steps to reproduce below:]

1. Clicked 'install' button from package installer

**Atom Version**: 0.206.0
**System**: Mac OS X 10.10.3
**Thrown From**: [project-runner](https://github.com/hirohisa/atom-project-runner) package, v0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'prototype' of undefined

```
At /Users/rajsingh/.atom/packages/project-runner/lib/project-runner-view.coffee:4

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/rajsingh/.atom/packages/project-runner/lib/project-runner-view.coffee:4:199)
  at /Users/rajsingh/.atom/packages/project-runner/lib/project-runner-view.coffee:7:3
  at Object.<anonymous> (/Users/rajsingh/.atom/packages/project-runner/lib/project-runner-view.coffee:71:5)
  at Object.<anonymous> (/Users/rajsingh/.atom/packages/project-runner/lib/project-runner-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/rajsingh/.atom/packages/project-runner/lib/project-runner.coffee:1:21)
  at Object.<anonymous> (/Users/rajsingh/.atom/packages/project-runner/lib/project-runner.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:707:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:255:12)
  at PackageDetailView.module.exports.PackageDetailView.activate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:163:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:201:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:235:24
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at PackageManager.module.exports.Emitter.emitSlow (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:154:47)
  at PackageManager.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:107:30)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:546:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:369:26
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -1:44.7.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:44.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:43.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:43.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:42.9.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:42.9.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -1:40.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:24.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:21 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
     -1:20.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:20.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:19.3.0 fuzzy-finder:toggle-buffer-finder (atom-text-editor.editor.is-focused)
     -1:18.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:18.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:55 settings-view:open (atom-text-editor.editor.is-focused)
     -0:49.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "language-javascript-jsx"
    ],
    "themes": [
      "atom-light-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
emmet, v2.3.10
javascript-snippets, v1.0.0
jshint, v1.3.7
language-haml, v0.21.0
language-javascript-semantic, v0.2.1
linter, v0.12.6
minimap, v4.9.4
travis-ci-status, v0.15.0

# Dev
No dev packages
```

**Comment by hirohisa** [comment]
Sorry, Im late.

Fix by #9. Bump version to `0.3.0`, please update
