### ISSUE TITLE
Uncaught Error: Cannot find module 'ansi-to-html'

### ISSUE THREAD

**Issue by benjavides** [hirohisa/atom-project-runner#7]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [project-runner](https://github.com/hirohisa/atom-project-runner) package, v0.2.0

### Stack Trace

Uncaught Error: Cannot find module 'ansi-to-html'

```
At module.js:336

Error: Cannot find module 'ansi-to-html'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\Benjamín\AppData\Local\atom\app-1.0.15\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\Benjamín\.atom\packages\project-runner\lib\project-runner-view.coffee:2:14)
  at Object.<anonymous> (C:\Users\Benjamín\.atom\packages\project-runner\lib\project-runner-view.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\Benjamín\AppData\Local\atom\app-1.0.15\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\Benjamín\.atom\packages\project-runner\lib\project-runner.coffee:1:21)
  at Object.<anonymous> (C:\Users\Benjamín\.atom\packages\project-runner\lib\project-runner.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\Benjamín\AppData\Local\atom\app-1.0.15\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\Benjamín\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:761:34)
  at Package.module.exports.Package.activateConfig (C:\Users\Benjamín\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:263:14)
  at PackageDetailView.module.exports.PackageDetailView.activateConfig (C:\Users\Benjamín\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:212:26)
  at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (C:\Users\Benjamín\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:156:12)
  at PackageDetailView.module.exports.PackageDetailView.loadPackage (C:\Users\Benjamín\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:168:21)
  at C:\Users\Benjamín\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:298:17
  at Emitter.module.exports.Emitter.emit (C:\Users\Benjamín\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (C:\Users\Benjamín\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-manager.js:588:27)
  at C:\Users\Benjamín\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-manager.js:379:26
  at exit (C:\Users\Benjamín\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-manager.js:60:16)
  at triggerExitCallback (C:\Users\Benjamín\AppData\Local\atom\app-1.0.15\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\Benjamín\AppData\Local\atom\app-1.0.15\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

### Commands

```
  5x -2:53.6.0 script:run (atom-text-editor.editor.is-focused)
  2x -2:33.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  6x -1:10.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:08.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "linter-flake8",
      "linter-pylint",
      "linter",
      "linter-pep8",
      "atom-beautify",
      "script"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.2.4
atom-material-ui, v0.6.1
autocomplete-python, v0.5.4
drop-up, v0.4.0
file-type-icons, v0.7.3
pdf-view, v0.27.0

# Dev
No dev packages
```

**Comment by hirohisa** [comment]
Sorry, I'm late. 🙇 

First, support to atom version `1.x` by #9. Bump version to `0.3.0`, please update.

Second,
> Cannot find module 'ansi-to-html'

try:
```
$ npm install ansi-to-html
```
